### PR TITLE
Restuarant App

### PR DESCRIPTION
**Pull request by taiwo2**
Create a bare-bones homepage for a restaurant. Include an image, headline, and some copy about how wonderful the restaurant is. It’s okay to hard-code these into the HTML for now just to see how they look on the page.

### CODE REVIEW

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Invalid Code Review Request :x: 

__Hi @taiwo2, I commend you for the great effort put into this project. However, I have to mark the project as invalid due to the following reasons:__

- [ ] Your repo does not look professional
- You did not work with git-flow  (<a href="https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/git_flow_requirement.png">screenshot</a> from Pathwright)
- Please check [this article](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59882084/) for a refresher of how to set up Git Flow.

_**As your code review request was invalidated, it does not count for the code review limit.**_

* * *
**Please, do not open a new Pull Request for subsequent reviews. You should use the same Pull Request submitted for the first review unless it is requested otherwise.**

**Always post your inquiries and questions on this PR thread as a comment. You can mention me (@teekaytech) so I can see your comments and respond.**

* * * 

**_You can reach out to me on Twitter (@ola_lere), Github(@teekaytech), or slack (@taofeekolalere )_**

Happy Coding :man_technologist:

**Comment by taiwo2** [comment]
@teekaytech Its like you did't check the repo at all.
kindly check very well
I had follow git flow

**Comment by teekaytech** [comment]
> @teekaytech Its like you did't check the repo at all.
> kindly check very well
> I had follow git flow

Hi @taiwo2 

Looks like you don't understand. You created your pull request from the feature branch (restaurant) to the master branch. This is wrong. You should create your pull request from the feature branch (restaurant) to the development branch, not the master branch.. This implies that your base branch should be the `develop` branch, not the master branch.

Happy coding!

**Comment by taiwo2** [comment]
hey @teekaytech Noted, thanks for clarification

**Review by Torres-ssf — APPROVED** [review]
### PR Approved :+1: :clap: 
Hello @taiwo2 :hand: 
Great job on this project.
Good luck with the next one

Happy coding :computer: 
**Sérgio Torres**

**Pull request merged**
